# -*- coding: utf-8 -*-
"""6. Python 101 - Files - Skeleton.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MdjkQ9A2Yzu52hVireRu1Xh5uCj0mcBP

# 1. TEXT FILES

- open() is the key function to handle files 
- open() function takes two parameters: (1) filename (2) mode.
- Modes for files opening: 

    - "r" - Read - Default value. Opens a file for reading, error if the file does not exist
    - "a" - Append - Opens a file for appending, creates the file if it does not exist
    - "w" - Write - Opens a file for writing, creates the file if it does not exist
    - "x" - Create - Creates the specified file, returns an error if the file exists

- files can be used in a binary or text mode

    - "t" - Text - Default value. Text mode
    - "b" - Binary - Binary mode (e.g. images)
"""

# In order to access data on Google Drive, you need to mount the drive to access it's content
from google.colab import drive
drive.mount('/content/drive')

# Open and read text file
f = open('/content/drive/MyDrive/1.1 Python for Financial Analysis - Course Package/Part 1. Python Programming Fundamentals/sample_text_file.txt', 'r')
print(f.read())

# readline will be used to read the first line
f = open('/content/drive/MyDrive/1.1 Python for Financial Analysis - Course Package/Part 1. Python Programming Fundamentals/sample_text_file.txt', 'r')
print(f.readline())

# You can open the file and append content to it
f = open('/content/drive/MyDrive/1.1 Python for Financial Analysis - Course Package/Part 1. Python Programming Fundamentals/sample_text_file.txt', 'a')
f.write('This is a new line that i wrote on the sample file')

# close the file and let's check its content
f.close()

# Let's open the updated file after writing new content to it

with open('/content/drive/MyDrive/1.1 Python for Financial Analysis - Course Package/Part 1. Python Programming Fundamentals/sample_text_file.txt', 'r') as f:
   text_data = f.readlines()

with open('/content/drive/MyDrive/1.1 Python for Financial Analysis - Course Package/Part 1. Python Programming Fundamentals/sample_text_file.txt', 'r') as f:
   text_data = f.readlines()

# split into a list of words

"""**MINI CHALLENGE #1:**
- **Read the file 'fruits_input.txt'**
- **compare the text file content to the list my_fruits = ["Apple", "Pepper", "Orange", "Watermelon", "Tomatoes"]**

"""

with open('/content/drive/MyDrive/1.1 Python for Financial Analysis - Course Package/Part 1. Python Programming Fundamentals/fruits_input.txt', 'r') as f:
  random_fruits = f.readlines()

random_fruits

random_fruits = [char.rstrip('\n') for char in random_fruits]

random_fruits

my_fruits = ["Apple", "Pepper", "Orange", "Watermelon", "Tomatoes"]

selected = [x for x in my_fruits if x in random_fruits ]

selected



"""# 2. CSV FILES"""

# you can read csv files using "csv.reader"
import csv 
with open('/content/drive/MyDrive/1.1 Python for Financial Analysis - Course Package/Part 1. Python Programming Fundamentals/sample_csv_file.csv') as f:
  readCSV= csv.reader(f,delimiter = ',')
  data = list(readCSV)

# Let's view the first row
data

# Let's view the second row
data[1]
data[3]

# Combine first and last names together to generate full_name
fullname = []

for name in data[1:4]:
   fullname.append(name[0]+ " "+ name[1])

fullname

dollarvalue=[]
for dollar in data[1:4]:
  dollarvalue.append(dollar[5])

dollarvalue

"""**MINI CHALLENGE #2:**
- **Read the CSV file entitled "S&P500_Stock_data.csv" and print out the heading**
- **Print out the first 5 rows of data**

"""

with open('/content/drive/MyDrive/1.1 Python for Financial Analysis - Course Package/Part 1. Python Programming Fundamentals/S_P500_Stock_Data.csv') as f:
  spcsv = csv.reader(f,delimiter = ',')
  spfive = list(spcsv)

spfive

spfive[1:6]

selected = list(spfive[1:6])

selected

"""# EXCELLENT JOB!

# MINI CHALLENGE SOLUTIONS:

**MINI CHALLENGE #1:**
- **Read the file 'fruits_input.txt'**
- **compare the text file content to the list my_fruits = ["Apple", "Pepper", "Orange", "Watermelon", "Tomatoes"]**
"""

my_fruits = ["Apple", "Pepper", "Orange", "Watermelon", "Tomatoes"]

with open("/content/drive/My Drive/Colab Notebooks/Python & ML in Finance/Part 1. Python Programming Fundamentals/fruits_input.txt", "r") as file:
    all_fruits = file.readlines()

all_fruits = [char.rstrip('\n') for char in all_fruits]
Selected_fruits = [i for i in all_fruits if i in my_fruits]

print(Selected_fruits)

"""**MINI CHALLENGE #2:**
- **Read the CSV file entitled "S&P500_Stock_data.csv" and print out the heading**
- **Print out the first 5 rows of data**
"""

import csv
with open("/content/drive/My Drive/Colab Notebooks/Python & ML in Finance/Part 1. Python Programming Fundamentals/S&P500_Stock_Data.csv", "r") as csvfile:
    readCSV = csv.reader(csvfile, delimiter=',')
    stock = list(readCSV)

print(stock)

print(stock[0])

selected = []
for row in stock[1:6]:
    selected.append(row)

selected

